swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
tags:
  - name: User Module
  - name: User Account
  - name: User Transactions
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          type: boolean
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          type: boolean
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /accounts:
    get:
      tags:
        - User Account
      summary: accounts database
      description: Get all users accounts
      parameters:
        - in: header
          type: boolean
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Users accounts retrieved successully
          schema:
            $ref: "#/definitions/AllAccountsResponse"
        "400":
          description: Accounts not found
        "500":
          description: Internal Server Error
  /user/account:
    get:
      tags:
        - User Account
      summary: Transaction view
      description: API for all user transactions
      parameters:
        - in: header
          type: boolean
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/AccountResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/account/transactions/{transactionID}:
    get:
      tags:
        - User Transactions
      summary: Get one transaction
      description: API for a user transaction
      parameters:
        - in: header
          type: boolean
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: transactionID
          required: true
          description: the transaction ID
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    post:
      tags:
        - User Transactions
      summary: Add new transaction
      description: API for add a user transaction
      parameters:
        - in: header
          type: boolean
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: transactionID
          required: true
          description: the transaction ID
          type: integer
        - in: body
          name: body
          description: Add transaction
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction added succesfully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: Update User Transactions
      description: Update transaction informations
      parameters:
        - in: path
          name: transactionID
          required: true
          description: the transaction ID
          type: integer
        - in: header
          type: boolean
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user transaction
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      produces:
        - application/json
      responses:
        "200":
          description: User transaction updated successully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - User Transactions
      summary: Delete a Transaction
      description: Delete transaction informations
      parameters:
        - in: path
          name: transactionID
          required: true
          description: the transaction ID
          type: integer
        - in: header
          type: boolean
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Transaction deleted successully
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  AllAccountsResponse:
    type: object
    properties:
      status:
        type: string
      accounts:
        type: array
        items:
          type: object

  AccountResponse:
    type: object
    properties:
      status:
        type: string
      date:
        type: integer
      description:
        type: string
      amount:
        type: integer
      balance:
        type: integer
  Transaction:
    type: object
    properties:
      id:
        type: integer
      createdAt:
        type: string
        format: date-time
      name:
        type: string
      amount:
        type: integer
      balance:
        type: integer
      type:
        $ref: "#/definitions/TransactionsType"
      category:
        $ref: "#/definitions/TransactionsCategory"
      notes:
        type: string
  TransactionsType:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
  TransactionsCategory:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
  UpdateTransaction:
    type: object
    properties:
      status:
        type: string
      transactionType:
        type: string
      category:
        type: string
      notes:
        type: string
